server:
  port: 8000
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
spring:
  application:
    name: facade-gateway
  cloud:
    gateway:
      routes:
        - id: core_route_1
          uri: http://23.20.5.224:8100
          predicates:
            - Path=/api/v1/**
            - Weight=group1, 5
        - id: core_route_2
          uri: http://23.20.5.224:8101
          predicates:
            - Path=/api/v1/**
            - Weight=group1, 5
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos